runs:
  using: "composite"
  steps:
    - name: Get AWS Region name
      id: _AWS_REGION
      run: |
        echo "_AWS_REGION=$(sed -n 's/^_AWS_REGION=//p' Makefile)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume:  ${{ inputs.secret_input }}  #IAM Role ARN
        role-session-name: ${{ github.event.repository.name }}_${{ github.base_ref}}_${{github.actor}}
        aws-region: ${{ steps._AWS_REGION.outputs._AWS_REGION }}

    - name: Configure Awscli
      run: make awscli-ci
      env:
        _AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        _AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        _AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
      shell: bash