#!/bin/bash
echo $_AWS_PROFILE

### Configure base profile
aws configure set aws_access_key_id $_AWS_ACCESS_KEY_ID --profile $_AWS_PROFILE
aws configure set aws_secret_access_key $_AWS_SECRET_ACCESS_KEY --profile $_AWS_PROFILE
aws configure set aws_session_token $_AWS_SESSION_TOKEN --profile $_AWS_PROFILE
aws configure set region $_AWS_REGION --profile $_AWS_PROFILE