name: Deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      AWS_GITHUB_OIDC_ROLE_ARN:
        required: true

env:
  _ENV: ${{ inputs.env }}
    
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install & Setup Terraform-Terragrunt & Setup AWS
        id: setup
        uses: ./.github/actions/terraform-aws-setup
        with:
          secret_input: ${{ secrets.AWS_GITHUB_OIDC_ROLE_ARN }}

      - name: Deployment Plan
        run: make plan
      
      - name: Deploy
        run: make apply-ci